### PR TITLE
Fix for files with parenthesis where the filename does not match the filename of and in the json file

### PR DESCRIPTION
**Pull request by rizz360**
This should close issue #59. Will do some more testing and report back.

### CODE REVIEW

**Comment by rizz360** [comment]
Sorry for the duplicate commits, should have created a separate branch on my fork.

**Comment by TheLastGimbus** [comment]
Umm... this was solved in #27 (at least it should be)...

**Comment by rizz360** [comment]
I thought so too, but the titles in the json files do not include the parenthesis. See example in issue #59

**Comment by jmigual** [comment]
Yes, I've just seen that there are some files that have:

- Name: `file(1).jpg`
- JSON file name: `file.jpg(1).json`
- `title` field inside JSON: `file.jpg`

So this PR sounds useful at fixing that. My only concern is what happens if the file already has a parenthesis. Something like `Photo (christmass)(1).jpg`.

**Comment by rizz360** [comment]
The regexp does not match for (christmas). It will only match at (1).  
It will skip files with a name like IMG_1234(1)(1).JPG or IMG_1234(1)(2).JPG

**Comment by rizz360** [comment]
Did some more testing and it works really well, so I'll remove the draft tag.

**Comment by TheLastGimbus** [comment]
## Hi guys, I'm back!

1. @jmigual I see you handled some review and organisation stuff for me already - thanks very much!
2. I ran this quickly on relatively small sample, and:
  - before: `Files for which we couldn't find json: 435`
  - after: `Files for which we couldn't find json: 429` - nice!
  Rest of the stats stayed the same... I will take a closer look to see whether we can meybe optimise/shrink it more :thinking: 
3. I think I need to make some CI to quickly test many cases :sweat_smile: - could you guys @rizz360 @jmigual maybe give out some sample photos that can be made public? Some edget cases maybe, weird broken exifs, weird `photo(1).jpg -> PHOTO.JPG(1).JSON` stuff kinda things? (and also the normal stuff) Maybe 10 or 20 photos?

**Review by TheLastGimbus — APPROVED** [review]

**Comment by TheLastGimbus** [comment]
I will allow myself to use this thread as a test space for new CI :)

**Comment by TheLastGimbus** [comment]
Test dupa12

**Comment by TheLastGimbus** [comment]
!time

**Comment by TheLastGimbus** [comment]
!time

**Comment by TheLastGimbus** [comment]
!time

**Comment by TheLastGimbus** [comment]
!time

**Comment by TheLastGimbus** [comment]
!time

**Comment by TheLastGimbus** [comment]
!time

**Comment by TheLastGimbus** [comment]
!time

**Comment by TheLastGimbus** [comment]
!time

**Comment by TheLastGimbus** [comment]
!time

**Comment by rizz360** [comment]
> I think I need to make some CI to quickly test many cases 😅 - could you guys @rizz360 @jmigual maybe give out some sample photos that can be made public? Some edget cases maybe, weird broken exifs, weird `photo(1).jpg -> PHOTO.JPG(1).JSON` stuff kinda things? (and also the normal stuff) Maybe 10 or 20 photos?

Hi!
Thanks for the update! I might get some time tomorrow to collect some sample pictures. Do you want them as part of the repository or as a simple download link (e.g. wetransfer)?

**Comment by TheLastGimbus** [comment]
So for the past ~2 hours I tried 10 different scripts to download stuff from Google Drive, because I thought GitHub will have slow download time :facepalm: 

But yeah, drop me some wetransfer link. At best, take them directly from you takeout, with their jsons (like they were truly from takeout)

**Comment by TheLastGimbus** [comment]
!time

**Comment by TheLastGimbus** [comment]
!time

**Comment by TheLastGimbus** [comment]
!time

**Comment by rizz360** [comment]
> But yeah, drop me some wetransfer link. At best, take them directly from you takeout, with their jsons (like they were truly from takeout)

Here you go: https://we.tl/t-h2y7Y0FiCr
I don't have the _super-raw_ files anymore. By running the script, the original files are changed as well. But apart from having the metadata already fixed, the script handles them the same.

**Comment by jmigual** [comment]
Hi, glad to see that you are back 😊 . I can also provide you with some files too, I just have to check that there's nothing private so it can be used. As soon as I have it I'll send it to you.

**Pull request merged**
