### PR TITLE
Use pathlib

### PR DESCRIPTION
**Pull request by jmigual**
This PR moves all the path handling to pathlib instead of all the string parsing.

This will make easier to:

- Handle directories
- Handle file extensions
- Renaming files

### CODE REVIEW

**Comment by jmigual** [comment]
Updated to newest changes

**Comment by TheLastGimbus** [comment]
Sorry, I really wanted to add some changes and made some merge conflicts here :sweat_smile: 

I'm skeptical about merging this, as it changes a lot, but I'll take a look later

**Comment by jmigual** [comment]
No problem about the conflicts 😊. I understand if you are skeptical. I did this PR as it simplifies a lot the path handling and should allow for faster development. I basically just replaced almost all the `_os.X` calls related to paths with pathlib equivalents. This way we have a uniform way of acessing to file names, directories and so.

My biggest question is that I've made the `for_all_files_recursive()` function non-recursive by using `Path.rglob('*')` and I'm not sure whether there was a reason for it to be recursive.

**Comment by jmigual** [comment]
This should also make it easier to solve #8 as there will be a lot of path handling

**Comment by TheLastGimbus** [comment]
Okay so I got this exception:

```python
Traceback (most recent call last):
  File "__main__.py", line 613, in <module>
    main()
  File "__main__.py", line 544, in main
    for_all_files_recursive(
  File "__main__.py", line 124, in for_all_files_recursive
    folder_function(file)
  File "__main__.py", line 256, in remove_duplicates
    duplicates = find_duplicates(dir, lambda f: (is_photo(f) or is_video(f)))
  File "__main__.py", line 249, in find_duplicates
    dups.remove(original)
ValueError: list.remove(x): x not in list
```

**Comment by jmigual** [comment]
Okay, my fault. I used the wrong variable one assigning the value of `original`. It is fixed now.

**Comment by TheLastGimbus** [comment]
Another one:
```python
Traceback (most recent call last):
  File "__main__.py", line 613, in <module>
    main()
  File "__main__.py", line 572, in main
    for_all_files_recursive(
  File "__main__.py", line 128, in for_all_files_recursive
    file_function(file)
```
Looks like `copy_to_target` isn't migrated

By the way, I need to ask @bitsondatadev and @rtadams89 - do you have any big changes WIP that will conflict with this if I merge it?

**Comment by rtadams89** [comment]
No WIP at all from me

**Comment by jmigual** [comment]
Fixed let's hope it's the last one 😅

**Comment by bitsondatadev** [comment]
GFI! I'm starting on #10 tomorrow

**Comment by TheLastGimbus** [comment]
I think *thats* the last:
```python
DONE! FREEDOM!

Final statistics:
Files copied to target folder: 1527
Removed duplicates: 408
Files where inserting correct exif failed: 160
Traceback (most recent call last):
  File "__main__.py", line 613, in <module>
    main()
  File "__main__.py", line 588, in main
    f.write("\n".join(s_cant_insert_exif_files))
```
Writing stats to file isn't migrated - I don't know if it would be better to save `s_cant_insert_exif_files` and other lists as just plain text absolute path list, or somehow map it at the end - you decide :+1:

**Comment by jmigual** [comment]
Yep, thanks! I did have a takeout copy and I forgot to test it 😓 sorry

**Pull request merged**
