### PR TITLE
change in bin/gpth.dart

### PR DESCRIPTION
**Pull request by 8975023089**

### CODE REVIEW

**Comment by 8975023089** [comment]
approved

**Comment by 8975023089** [comment]
approved

**Comment by TheLastGimbus** [comment]
Um... Why?

**Comment by TheLastGimbus** [comment]
idk what you wanted, but this line is required to maintain 💅clean💅 - if you want faster zip-unzip-gpth workflow etc, just unzip manually and use `--copy` :+1:

**Pull request closed without merging**
