### PR TITLE
Add 'NaN' string handling in altitude

### PR DESCRIPTION
**Pull request by Witti**
I found some images with a sting containing 'NaN' for the altitude value so I added a check for this case.

### CODE REVIEW

**Comment by TheLastGimbus** [comment]
Could you hand me a file+json that was causing this? I would like to see why this is happening

Actually, now that I'm looking at it...
```python
# fetches geo data from the photos editor first.
longitude = float(json['geoData']['longitude'])
latitude = float(json['geoData']['latitude'])
altitude = float(json['geoData']['altitude'])

# fallbacks to GeoData Exif if it wasn't set in the photos editor.
# https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/pull/5#discussion_r531792314
longitude = float(json['geoData']['longitude'])
latitude = float(json['geoData']['latitude'])
altitude = json['geoData']['altitude']
# Prioritise geoData set from GPhotos editor
```
This seems very weird... something went very wrong whem me and @DalenW were merging this :sweat_smile: 

@DalenW, should this be here? Why do we get `lat/lng/alt` pretty much two times, except we don't wrap altitute in `float` the second time :sweat_smile: :laughing:? We also don't wrap it in `float` inside the `if`...

I think that solution to this PR is acutally simplifing this, but I want to see how you got some "NaN's" in there, and waiting for your thoughts on that @Witti

**Comment by DalenW** [comment]
Ah, we check twice because we can either pull from the coordinates set by the photo editor first, and then we fall back to the coords from the photo itself. But looking back on this code, I'm now confused by what I wrote. because I'm overwriting variables? idk, full code pasted below.

```python

# fetches geo data from the photos editor first.
longitude = float(json['geoData']['longitude'])
latitude = float(json['geoData']['latitude'])
altitude = float(json['geoData']['altitude'])

# fallbacks to GeoData Exif if it wasn't set in the photos editor.
# https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/pull/5#discussion_r531792314
longitude = float(json['geoData']['longitude'])
latitude = float(json['geoData']['latitude'])
altitude = json['geoData']['altitude']
# Prioritise geoData set from GPhotos editor
if longitude == 0 and latitude == 0:
    longitude = float(json['geoDataExif']['longitude'])
    latitude = float(json['geoDataExif']['latitude'])
    altitude = json['geoDataExif']['altitude']

```

I think I can remove the first 3 variable declarations and it'll still work. Also, we could wrap the altitude declaration in float(), not sure why I didn't do that. 

Every `*.json` file I have has `0.0` in place of empty coords, like so:

```json
"geoData": {
    "latitude": 0.0,
    "longitude": 0.0,
    "altitude": 0.0,
    "latitudeSpan": 0.0,
    "longitudeSpan": 0.0
  },
  "geoDataExif": {
    "latitude": 0.0,
    "longitude": 0.0,
    "altitude": 0.0,
    "latitudeSpan": 0.0,
    "longitudeSpan": 0.0
  },
```

So if it's throwing NaN, either something else is there, or the JSON doesn't exist? But at that point it shouldn't attempt to set the new Exif data in the first place. 

Ultimately, I'd like to see the file as well. Maybe something changes and `geoData` isn't there if the photo doesn't have coords.

**Comment by Witti** [comment]
IMG_0023

```
{
  "title": "IMG_0023.JPG",
  "description": "",
  "imageViews": "0",
  "creationTime": {
    "timestamp": "1536508857",
    "formatted": "09.09.2018, 16:00:57 UTC"
  },
  "modificationTime": {
    "timestamp": "1606847912",
    "formatted": "01.12.2020, 18:38:32 UTC"
  },
  "photoTakenTime": {
    "timestamp": "1223409864",
    "formatted": "07.10.2008, 20:04:24 UTC"
  },
  "geoData": {
    "latitude": 48.21149826049805,
    "longitude": 16.360666275024414,
    "altitude": "NaN",
    "latitudeSpan": 0.0,
    "longitudeSpan": 0.0
  },
  "geoDataExif": {
    "latitude": 0.0,
    "longitude": 0.0,
    "altitude": 0.0,
    "latitudeSpan": 0.0,
    "longitudeSpan": 0.0
  },
  "googlePhotosOrigin": {
    "fromPartnerSharing": {
    }
  }
}
````

**Comment by Witti** [comment]
The json file itself is broken in this case. It seems that google added a wrong value for the altitude. 
I have multiple files in my export with exactly the same issue.

**Comment by DalenW** [comment]
Huh. I wonder if wrapping altitude in a float would catch this. I try to stay away from Python, I usually do Ruby and JS.

**Comment by DalenW** [comment]
It looks like it could catch this...

```python
>>> float(0)
0.0
>>> float("NaN")
nan
>>>
```

**Comment by DalenW** [comment]
So what if we did this.

```python

# fallbacks to GeoData Exif if it wasn't set in the photos editor.
# https://github.com/TheLastGimbus/GooglePhotosTakeoutHelper/pull/5#discussion_r531792314
longitude = float(json['geoData']['longitude'])
latitude = float(json['geoData']['latitude'])
altitude = float(json['geoData']['altitude'])
# Prioritise geoData set from GPhotos editor
if longitude == 0 and latitude == 0:
    longitude = float(json['geoDataExif']['longitude'])
    latitude = float(json['geoDataExif']['latitude'])
    altitude = float(json['geoDataExif']['altitude'])

coords = [longitude, latitude, altitude]

for i in range(len(coords)):
  if coords[Ii == nan:
    coords[i] = 0.0
    

```

The rest of the code could be cleaned up too...

**Comment by Witti** [comment]
Fixed by #55

**Comment by TheLastGimbus** [comment]
By the way - I want to rant 🔥

Often, the way things are in closed vs open source world are - open source stuff is often fun, experimental, and offers a lot of tweaking, but because of underpayment, it breaks more often, because there isn't enough manpower to test and fix it

Closed source doesn't give you tweaking, but "just works"

**"Just works?"**

We are here, fucking with this *simple export* feature for few months, and I keep getting one new issue per 2 weeks that Google changed/exported some super weird value which doesn't make any sense

All of this, this whole repo wouldn't exist, if there were a single person who just listened. If there was any "send feedback" button which anyone actually read


If this is the way it "just works", then I boy sure I want open source to break all the time

**Pull request closed without merging**
