### PR TITLE
Guessing date/time from common filename patterns, if other methods fail

### PR DESCRIPTION
**Pull request by hheimbuerger**
### Background

If all reliable methods of identifying a timestamp for a photo fail (in particular the extraction from the metadata json), photos currently receive the timestamp of the time the script was executed.

### Overview

This PR adds a new CLI argument: `--guess-timestamp-from-filename`

If set, after trying all other methods of determining the timestamp, the filename will be searched for a handful of predefined regex patterns. If one of those matches, it will be used to apply the date/time.

### Results

In my case, this reduced the number of 'unsorted' files from 1492 to 22. And those 22 really have no discernible date contained in them — in fact, I have no idea where most of them come from or when they were taken.

Examples of filenames that are recognized by this implementation, as found in my personal Google Photos database (these should mostly come from earlier generation Nexus and Samsung phones):
* `Screenshot_20190919-053857_Camera-edited.jpg`
* `IMG_20190509_154733-edited.jpg`
* `MVIMG_20190215_193501.MP4`
* `IMG_20190221_112112042_BURST000_COVER_TOP.MP4`
* `Screenshot_2019-04-16-11-19-37-232_com.google.a.jpg`

### Implementation notes

A small refactoring is included (as a separate commit to improve readability), which factors out the format pattern used to write (and also indirectly to parse) date strings into EXIF. I just did that because I needed to use that format pattern as well and didn't want to create yet another hardcopy.

* There's not yet a statistical counter, to see for how many files this method was applied, as there is for some of the other methods (e.g. `s_date_from_folder_files`).
* In a quite possibly misguided attempt at guessing false positives, the century is expected to be `20`, and it won't accept photos with a timestamp in the 20th or 22nd century.

You're welcome to modify, use, or discard any parts, or the PR as a whole, whichever way you see fit. I'm also happy to discuss and you may even request changes, but I'm pretty much done with my conversion project and will leave Google Photos for good. So I might opt not to do major implementation work myself.

### CODE REVIEW

**Comment by TheLastGimbus** [comment]
Sorry for leaving you out for so long

All of this seems really nice! I'm really lazy right now and don't have time to write tests for it - do you assure me that it's working nicely and doesn't break stuff for people not-using it?

If so, I'll be happy to merge! Could you also add some mention about it in README please?

**Comment by hheimbuerger** [comment]
@TheLastGimbus Hey, no worries about the time, I just wanted to give back, Thank _you_ so much for building this in the first place, I don't know what I would have done without it.

As for the assurance... I mean of course I cannot assure you that. I did review the changes once again and they appear innocuous enough, but who knows what we both missed. I also never really tested it without the new CLI argument present, because I 'tested' it on the one task I needed to get done, but of course my task required the argument, that's why I built it.

I'll absolutely add it to the README and I think I'll also take out the Python 3.8 requirement. Not worth it for that one bit of syntactical sugar.

And afterwards, maybe we could convince @tkuenzle to maybe take this over for his own efforts, or at least test it for us, as it appears he's already been trying it (#112)? 😁 I don't know, I don't have any other idea how to move this forward sensibly.

**Comment by hheimbuerger** [comment]
@TheLastGimbus Added a note to the README and removed the assignment expression (from Python 3.8+).

Note that I haven't run this code again, because I don't even have a Google Takeout dump around right now. So this is even less tested than before.

Someone needs to test this before merging.

**Review by rud — APPROVED** [review]

**Comment by leesherwood** [comment]
If it helps, I ran this against my own Takeout and all seems fine.

Before
```
# This file contains list of files where there was no way to set correct date!
# You probably want to set their dates manually - but you can delete this if you want
./Takeout/Google Photos/Photos from 2020/MVIMG_20200502_125409.MP4
./Takeout/Google Photos/Photos from 2020/MVIMG_20200901_185335.MP4
./Takeout/Google Photos/Photos from 2018/MVIMG_20181225_175921.MP4
./Takeout/Google Photos/Photos from 2018/MVIMG_20181225_193508.MP4
./Takeout/Google Photos/Photos from 2018/MVIMG_20181225_193509.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190815_143314.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190531_204220.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20191030_154818.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190812_214912.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20191030_154830.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190417_150633.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190417_122927.MP4
./Takeout/Google Photos/Photos from 2019/original_3baa0456-e090-4a28-85b8-90edaa0f4ec0_M.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190422_170434.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190417_133209.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190609_133311.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190417_131620.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190702_144948.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190416_184356.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190416_184357.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190422_170435.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190417_112629.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20191031_194510.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190417_131624.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190417_132107.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190609_133513.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190518_171933.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190417_144124.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20191030_154834.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20191031_194513.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20191031_194512.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190417_145818.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190531_204231.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190417_144119.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190417_150636.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20191029_162207.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190826_141624.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190417_131052.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190705_201844.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190531_204120.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190417_130012.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190417_151407.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190417_131132.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190417_133917.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190417_130013.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190416_184257.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190417_131053.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20191109_155614.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190417_153549.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20191030_125918.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190418_144914.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190417_153616.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20191224_170849.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20191030_154707.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190417_151207.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190417_133905.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190417_133911.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190417_131121.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190418_121025.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190422_170447.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190416_184251.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190417_131132_1.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20191030_125658.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190531_204119.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190418_121741.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190418_121027.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190417_133912.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190417_131122.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190531_204044.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190531_204118.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190418_145205.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190416_184252.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20191109_155613.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190418_121017.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190810_190241.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20191029_162123.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190417_122147.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190418_121413.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190417_133923.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190418_122640.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20191030_132922.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190810_190240.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190417_120221.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20191030_125641.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190417_150301.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190518_193714.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20191030_154045.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190417_151357.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20191029_162108.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190417_131138.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190417_133908.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190417_133921.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190417_133909.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190417_122145.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190417_151356.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190417_150302.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190716_094240.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190812_213802.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190418_121011.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20191029_162131.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20191029_162125.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20191030_154108.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190417_133919.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190417_133918.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190417_133924.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190417_131048.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190418_122650.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190418_122644.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190812_214955.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190418_144700.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190418_121013.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20191030_125644.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190531_204118_1.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20191029_162245.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20191020_200449.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190531_204228.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190417_145814.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20191020_200448.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190531_204229.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190417_145816_1.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190417_132108.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20191029_162009.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20191029_152121.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190417_133821.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190417_133835.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190417_133837.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190417_123826.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190417_130053.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190705_201742.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190531_204217.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20191031_194509.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190417_145817.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190417_131614.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190417_130052.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190417_123827.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190418_121738.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190417_132057.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190826_141617.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20191006_120645.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190417_133826.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190826_141559.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20191031_194733.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190417_131611.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190417_131605.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20191031_194732.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190417_133833.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190417_133827.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190417_122928.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190502_174337.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190417_131607.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20191031_194731.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190502_174336.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190812_214117.MP4
./Takeout/Google Photos/Photos from 2019/MVIMG_20190417_133824.MP4
```

After
```
# This file contains list of files where there was no way to set correct date!
# You probably want to set their dates manually - but you can delete this if you want
./Takeout/Google Photos/Photos from 2019/original_3baa0456-e090-4a28-85b8-90edaa0f4ec0_M.MP4
```

And confirmed with rsync that it hasn't messed with any other files:
```
# rsync --dry-run -rai ./Takeout-Before/ ./Takeout-After/ 

sending incremental file list
.d..t....... ./
>f..t....... MVIMG_20181225_175921.MP4
>f..t....... MVIMG_20181225_193508.MP4
>f..t....... MVIMG_20181225_193509.MP4
>f..t....... MVIMG_20190416_184251.MP4
>f..t....... MVIMG_20190416_184252.MP4
>f..t....... MVIMG_20190416_184257.MP4
>f..t....... MVIMG_20190416_184356.MP4
>f..t....... MVIMG_20190416_184357.MP4
>f..t....... MVIMG_20190417_112629.MP4
>f..t....... MVIMG_20190417_120221.MP4
>f..t....... MVIMG_20190417_122145.MP4
>f..t....... MVIMG_20190417_122147.MP4
>f..t....... MVIMG_20190417_122927.MP4
>f..t....... MVIMG_20190417_122928.MP4
>f..t....... MVIMG_20190417_123826.MP4
>f..t....... MVIMG_20190417_123827.MP4
>f..t....... MVIMG_20190417_130012.MP4
>f..t....... MVIMG_20190417_130013.MP4
>f..t....... MVIMG_20190417_130052.MP4
>f..t....... MVIMG_20190417_130053.MP4
>f..t....... MVIMG_20190417_131048.MP4
>f..t....... MVIMG_20190417_131052.MP4
>f..t....... MVIMG_20190417_131053.MP4
>f..t....... MVIMG_20190417_131121.MP4
>f..t....... MVIMG_20190417_131122.MP4
>f..t....... MVIMG_20190417_131132.MP4
>f..t....... MVIMG_20190417_131132_1.MP4
>f..t....... MVIMG_20190417_131138.MP4
>f..t....... MVIMG_20190417_131605.MP4
>f..t....... MVIMG_20190417_131607.MP4
>f..t....... MVIMG_20190417_131611.MP4
>f..t....... MVIMG_20190417_131614.MP4
>f..t....... MVIMG_20190417_131620.MP4
>f..t....... MVIMG_20190417_131624.MP4
>f..t....... MVIMG_20190417_132057.MP4
>f..t....... MVIMG_20190417_132107.MP4
>f..t....... MVIMG_20190417_132108.MP4
>f..t....... MVIMG_20190417_133209.MP4
>f..t....... MVIMG_20190417_133821.MP4
>f..t....... MVIMG_20190417_133824.MP4
>f..t....... MVIMG_20190417_133826.MP4
>f..t....... MVIMG_20190417_133827.MP4
>f..t....... MVIMG_20190417_133833.MP4
>f..t....... MVIMG_20190417_133835.MP4
>f..t....... MVIMG_20190417_133837.MP4
>f..t....... MVIMG_20190417_133905.MP4
>f..t....... MVIMG_20190417_133908.MP4
>f..t....... MVIMG_20190417_133909.MP4
>f..t....... MVIMG_20190417_133911.MP4
>f..t....... MVIMG_20190417_133912.MP4
>f..t....... MVIMG_20190417_133917.MP4
>f..t....... MVIMG_20190417_133918.MP4
>f..t....... MVIMG_20190417_133919.MP4
>f..t....... MVIMG_20190417_133921.MP4
>f..t....... MVIMG_20190417_133923.MP4
>f..t....... MVIMG_20190417_133924.MP4
>f..t....... MVIMG_20190417_144119.MP4
>f..t....... MVIMG_20190417_144124.MP4
>f..t....... MVIMG_20190417_145814.MP4
>f..t....... MVIMG_20190417_145816_1.MP4
>f..t....... MVIMG_20190417_145817.MP4
>f..t....... MVIMG_20190417_145818.MP4
>f..t....... MVIMG_20190417_150301.MP4
>f..t....... MVIMG_20190417_150302.MP4
>f..t....... MVIMG_20190417_150633.MP4
>f..t....... MVIMG_20190417_150636.MP4
>f..t....... MVIMG_20190417_151207.MP4
>f..t....... MVIMG_20190417_151356.MP4
>f..t....... MVIMG_20190417_151357.MP4
>f..t....... MVIMG_20190417_151407.MP4
>f..t....... MVIMG_20190417_153549.MP4
>f..t....... MVIMG_20190417_153616.MP4
>f..t....... MVIMG_20190418_121011.MP4
>f..t....... MVIMG_20190418_121013.MP4
>f..t....... MVIMG_20190418_121017.MP4
>f..t....... MVIMG_20190418_121025.MP4
>f..t....... MVIMG_20190418_121027.MP4
>f..t....... MVIMG_20190418_121413.MP4
>f..t....... MVIMG_20190418_121738.MP4
>f..t....... MVIMG_20190418_121741.MP4
>f..t....... MVIMG_20190418_122640.MP4
>f..t....... MVIMG_20190418_122644.MP4
>f..t....... MVIMG_20190418_122650.MP4
>f..t....... MVIMG_20190418_144700.MP4
>f..t....... MVIMG_20190418_144914.MP4
>f..t....... MVIMG_20190418_145205.MP4
>f..t....... MVIMG_20190422_170434.MP4
>f..t....... MVIMG_20190422_170435.MP4
>f..t....... MVIMG_20190422_170447.MP4
>f..t....... MVIMG_20190502_174336.MP4
>f..t....... MVIMG_20190502_174337.MP4
>f..t....... MVIMG_20190518_171933.MP4
>f..t....... MVIMG_20190518_193714.MP4
>f..t....... MVIMG_20190531_204044.MP4
>f..t....... MVIMG_20190531_204118.MP4
>f..t....... MVIMG_20190531_204118_1.MP4
>f..t....... MVIMG_20190531_204119.MP4
>f..t....... MVIMG_20190531_204120.MP4
>f..t....... MVIMG_20190531_204217.MP4
>f..t....... MVIMG_20190531_204220.MP4
>f..t....... MVIMG_20190531_204228.MP4
>f..t....... MVIMG_20190531_204229.MP4
>f..t....... MVIMG_20190531_204231.MP4
>f..t....... MVIMG_20190609_133311.MP4
>f..t....... MVIMG_20190609_133513.MP4
>f..t....... MVIMG_20190702_144948.MP4
>f..t....... MVIMG_20190705_201742.MP4
>f..t....... MVIMG_20190705_201844.MP4
>f..t....... MVIMG_20190716_094240.MP4
>f..t....... MVIMG_20190810_190240.MP4
>f..t....... MVIMG_20190810_190241.MP4
>f..t....... MVIMG_20190812_213802.MP4
>f..t....... MVIMG_20190812_214117.MP4
>f..t....... MVIMG_20190812_214912.MP4
>f..t....... MVIMG_20190812_214955.MP4
>f..t....... MVIMG_20190815_143314.MP4
>f..t....... MVIMG_20190826_141559.MP4
>f..t....... MVIMG_20190826_141617.MP4
>f..t....... MVIMG_20190826_141624.MP4
>f..t....... MVIMG_20191006_120645.MP4
>f..t....... MVIMG_20191020_200448.MP4
>f..t....... MVIMG_20191020_200449.MP4
>f..t....... MVIMG_20191029_152121.MP4
>f..t....... MVIMG_20191029_162009.MP4
>f..t....... MVIMG_20191029_162108.MP4
>f..t....... MVIMG_20191029_162123.MP4
>f..t....... MVIMG_20191029_162125.MP4
>f..t....... MVIMG_20191029_162131.MP4
>f..t....... MVIMG_20191029_162207.MP4
>f..t....... MVIMG_20191029_162245.MP4
>f..t....... MVIMG_20191030_125641.MP4
>f..t....... MVIMG_20191030_125644.MP4
>f..t....... MVIMG_20191030_125658.MP4
>f..t....... MVIMG_20191030_125918.MP4
>f..t....... MVIMG_20191030_132922.MP4
>f..t....... MVIMG_20191030_154045.MP4
>f..t....... MVIMG_20191030_154108.MP4
>f..t....... MVIMG_20191030_154707.MP4
>f..t....... MVIMG_20191030_154818.MP4
>f..t....... MVIMG_20191030_154830.MP4
>f..t....... MVIMG_20191030_154834.MP4
>f..t....... MVIMG_20191031_194509.MP4
>f..t....... MVIMG_20191031_194510.MP4
>f..t....... MVIMG_20191031_194512.MP4
>f..t....... MVIMG_20191031_194513.MP4
>f..t....... MVIMG_20191031_194731.MP4
>f..t....... MVIMG_20191031_194732.MP4
>f..t....... MVIMG_20191031_194733.MP4
>f..t....... MVIMG_20191109_155613.MP4
>f..t....... MVIMG_20191109_155614.MP4
>f..t....... MVIMG_20191224_170849.MP4
>f..t....... MVIMG_20200502_125409.MP4
>f..t....... MVIMG_20200901_185335.MP4
```

**Comment by TheLastGimbus** [comment]
Okay - tests are green, and so many approvals from others! Really nice job guys! Big thanks!

**Pull request merged**
