### PR TITLE
try to fix fucking windoza again

### LINKED ISSUE #212: PathNotFoundException caused by leading or trailing spaces in file/directory names
Hi, ran into an issue caused by a trailing space somehow showing up at the end of one of my directories in the example below. The exception caused the program to exit.
```
PathNotFoundException: Cannot rename file to 'output\2021.06.20 wedding shower \2021-06-20 14_42_48-Zoom Meeting.png', path = 'input\Takeout\Google Photos\2021.06.20 wedding shower \2021-06-20 14_42_48-Zoom Meeting.png' (OS Error: The system cannot find the path specified.
, errno = 3)
#0      _checkForErrorResponse (dart:io/common.dart:42)
#1      _File.rename.<anonymous closure> (dart:io/file_impl.dart:318)
<asynchronous suspension>
#2      moveFiles.moveFile (package:gpth/moving.dart:132)
<asynchronous suspension>
#3      moveFiles (package:gpth/moving.dart:153)
<asynchronous suspension>
#4      main.<anonymous closure> (file:///d:/a/googlephotostakeouthelper/googlephotostakeouthelper/bin/gpth.dart:365)
<asynchronous suspension>
```

### Being lazy, I asked ChatGPT where to make the change in `moving.dart`
"I encountered an error that seems to be caused by a space at the end of the folder name in the below error. I think the solution would be to strip leading and trailing empty characters of file and folder names. Where should this change be made?"

and it recommended the following changes. Looked mostly correct to me, so am reporting this issue. Hope this helps! Greatly appreciate your work

### ChatGPT response
The change should be made where the file and folder paths are being constructed, specifically where the folder's name is defined and where the file is being moved or copied to.

Here is where you can make the changes:

Line 83-90: This is where the folder path is constructed. You can use Dart's trim method to remove leading and trailing white spaces from the file and folder names. Replace the existing lines with the following code:

```dart
final folder = Directory(
  p.join(
    output.path,
    (file.key ?? 'ALL_PHOTOS').trim(), // album or all
    divideToDates
        ? date == null
            ? 'date-unknown'.trim()
            : p.join(
                '${date.year}'.trim(),
                date.month.toString().padLeft(2, '0').trim(),
              )
        : '',
  ),
);
```
Line 107-110: This is where the file is being moved or copied. Again, you should trim the filename here:
```dart
final freeFile = findNotExistingName(
    File(p.join(folder.path, p.basename(file.value.path).trim())));
```
After these changes, your program should work correctly with folder or file names that have leading or trailing spaces.

### PR DESCRIPTION
**Pull request by TheLastGimbus**
should be tested by @a-chen but they are busy talking to chatgpt so merging it as-is because well whatever

closes #212

### CODE REVIEW

**Comment by TheLastGimbus** [comment]
Hey @a-chen - i'm actaully not sure whether to merge this... i would really need you to test this for me :eyes:

**Comment by a-chen** [comment]
Alright, let me try ._. Just takes a while

**Comment by TheLastGimbus** [comment]
Don't worry, for me it's just clicking a big green button

(the frustration in commits is at windoza, not at you, to be sure!)

**Comment by TheLastGimbus** [comment]
decided to merge it already, you can test the newest version to see if it at lease doesn't crash... if it still wont' work we will try to come up with something more 🤔

**Comment by a-chen** [comment]
=D thanks. I already had a workaround by writing a script. The next time I do a takeout, I'll try and report back if there are issues, many thanks Gimbus

**Comment by TheLastGimbus** [comment]
That's nice! Could you help me tho and run this, cause i don't have windows... if you still have your takeout somewhere :pray:

**Pull request merged**
